# Generated by Django 4.2.23 on 2025-07-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa produktu')),
                ('flavor', models.CharField(max_length=50, verbose_name='Smak')),
                ('brand', models.CharField(default='Dzik', max_length=50, verbose_name='Marka')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('capacity', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pojemność')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
                'ordering': ['name', 'flavor'],
            },
        ),
    ]
