# Generated by Django 4.2.23 on 2025-07-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name', 'flavor'], 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AddField(
            model_name='product',
            name='caffeine_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Zawartość kofeiny (mg)'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('energy_drink', 'Energy Drink'), ('zero_caffeine_drink', 'Zero Caffeine Drink'), ('vitamine_boost', 'Vitamine Boost'), ('vitamine_drink', 'Vitamine Drink')], default='energy_drink', max_length=50, verbose_name='Kategoria'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa'),
        ),
    ]
