# Generated by Django 4.2.23 on 2025-07-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0002_alter_product_options_product_caffeine_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain', models.CharField(choices=[('zabka', 'Żabka'), ('biedronka', 'Biedronka'), ('carrefour', 'Carrefour'), ('kaufland', 'Kaufland'), ('lidl', 'Lidl'), ('topaz', 'Topaz'), ('inter', 'Intermarche'), ('dino', 'Dino'), ('stokrotka', 'Stokrotka'), ('aldi', 'Aldi'), ('twoj_market', 'Twój market'), ('other', 'Inny')], max_length=30, verbose_name='Sieć')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Nazwa własna')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Szerokość (lat)')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Długość (lon)')),
                ('products', models.ManyToManyField(blank=True, related_name='shops', to='dzik.product', verbose_name='Dostępne produkty')),
            ],
            options={
                'verbose_name': 'Sklep',
                'verbose_name_plural': 'Sklepy',
            },
        ),
    ]
