# Generated by Django 4.2.23 on 2025-07-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0003_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Szablon sieci'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='chain',
            field=models.CharField(choices=[('zabka', 'Żabka'), ('biedronka', 'Biedronka'), ('carrefour', 'Carrefour'), ('kaufland', 'Kaufland'), ('other', 'Inny')], max_length=30, verbose_name='Sieć'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Szerokość (lat)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Długość (lon)'),
        ),
    ]
