# Generated by Django 4.2.23 on 2025-07-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0004_shop_is_template_alter_shop_chain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='chain',
            field=models.CharField(choices=[('zabka', 'Żabka'), ('biedronka', 'Biedronka'), ('carrefour', 'Carrefour'), ('kaufland', 'Kaufland'), ('lidl', 'Lidl'), ('topaz', 'Topaz'), ('inter', 'Intermarche'), ('dino', 'Dino'), ('stokrotka', 'Stokrotka'), ('aldi', 'Aldi'), ('twoj_market', 'Twój market'), ('other', 'Inny')], max_length=30, verbose_name='Sieć'),
        ),
    ]
