# Generated by Django 4.2.23 on 2025-07-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0005_alter_shop_chain'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo wyświetlane na mapie (zalecany rozmiar: 64x64px)', null=True, upload_to='shop_logos/', verbose_name='Logo sieci'),
        ),
    ]
