# Generated by Django 4.2.23 on 2025-07-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0006_shop_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='shops',
            field=models.ManyToManyField(blank=True, help_text='Wybierz sklepy gdzie ten produkt jest dostępny', related_name='products', to='dzik.shop', verbose_name='Dostępny w sklepach'),
        ),
    ]
