# Generated by Django 4.2.23 on 2025-07-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0007_remove_shop_products_product_shops'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-is_template', 'chain', 'name'], 'verbose_name': 'Sklep', 'verbose_name_plural': 'Sklepy'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='shops',
        ),
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='shops', to='dzik.product', verbose_name='Produkty w sklepie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='product',
            name='caffeine_content',
            field=models.CharField(choices=[('none', 'Bez kofeiny'), ('low', 'Niska (do 50mg)'), ('medium', 'Średnia (50-100mg)'), ('high', 'Wysoka (100-200mg)'), ('very_high', 'Bardzo wysoka (200mg+)')], default='none', max_length=20, verbose_name='Zawartość kofeiny'),
        ),
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pojemność'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('energy_drink', 'Energy Drink'), ('soft_drink', 'Napój gazowany'), ('water', 'Woda'), ('juice', 'Sok'), ('coffee', 'Kawa'), ('tea', 'Herbata'), ('other', 'Inne')], max_length=20, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flavor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Smak'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Zdjęcie produktu'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='chain',
            field=models.CharField(choices=[('zabka', 'Żabka'), ('biedronka', 'Biedronka'), ('lidl', 'Lidl'), ('kaufland', 'Kaufland'), ('auchan', 'Auchan'), ('carrefour', 'Carrefour'), ('tesco', 'Tesco'), ('netto', 'Netto'), ('polo_market', 'Polo Market'), ('freshmarket', 'Freshmarket'), ('other', 'Inny')], max_length=50, verbose_name='Sieć sklepów'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Czy to szablon dla całej sieci sklepów?', verbose_name='Szablon sieci'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Szerokość geograficzna'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo sklepu'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Długość geograficzna'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa sklepu'),
        ),
    ]
