# Generated by Django 4.2.23 on 2025-07-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0008_alter_shop_options_remove_product_shops_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Sklep', 'verbose_name_plural': 'Sklepy'},
        ),
        migrations.RemoveField(
            model_name='shop',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='shops',
            field=models.ManyToManyField(blank=True, help_text='Wybierz sklepy gdzie ten produkt jest dostępny', related_name='products', to='dzik.shop', verbose_name='Dostępny w sklepach'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Dzik', max_length=50, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='product',
            name='caffeine_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Zawartość kofeiny (mg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='capacity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pojemność'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('energy_drink', 'Energy Drink'), ('zero_caffeine_drink', 'Zero Caffeine Drink'), ('vitamine_boost', 'Vitamine Boost'), ('vitamine_drink', 'Vitamine Drink')], default='energy_drink', max_length=50, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dodania'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flavor',
            field=models.CharField(max_length=50, verbose_name='Smak'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Zdjęcie'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='chain',
            field=models.CharField(choices=[('zabka', 'Żabka'), ('biedronka', 'Biedronka'), ('carrefour', 'Carrefour'), ('kaufland', 'Kaufland'), ('lidl', 'Lidl'), ('topaz', 'Topaz'), ('inter', 'Intermarche'), ('dino', 'Dino'), ('stokrotka', 'Stokrotka'), ('aldi', 'Aldi'), ('twoj_market', 'Twój market'), ('other', 'Inny')], max_length=30, verbose_name='Sieć'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='is_template',
            field=models.BooleanField(default=False, verbose_name='Szablon sieci'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Szerokość (lat)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo wyświetlane na mapie (zalecany rozmiar: 64x64px)', null=True, upload_to='shop_logos/', verbose_name='Logo sieci'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Długość (lon)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nazwa własna'),
        ),
    ]
