# Generated by Django 4.2.23 on 2025-07-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0009_alter_shop_options_remove_shop_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shops',
        ),
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='shops', to='dzik.product', verbose_name='Produkty w sklepie'),
        ),
    ]
