# Generated by Django 4.2.23 on 2025-07-22 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0010_remove_product_shops_shop_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='products',
        ),
        migrations.CreateModel(
            name='ProductShopRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('is_available', models.BooleanField(default=True, verbose_name='Dostępny')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzik.product', verbose_name='Produkt')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dzik.shop', verbose_name='Sklep')),
            ],
            options={
                'verbose_name': 'Produkt w sklepie',
                'verbose_name_plural': 'Produkty w sklepach',
                'ordering': ['product__category', 'product__name', 'shop__chain'],
                'unique_together': {('product', 'shop')},
            },
        ),
    ]
