# Generated by Django 4.2.23 on 2025-07-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0011_remove_shop_products_productshoprelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='featured_products',
            field=models.ManyToManyField(blank=True, help_text='Główne produkty dostępne w tym sklepie', through='dzik.ProductShopRelation', to='dzik.product', verbose_name='Produkty w sklepie'),
        ),
    ]
