# Generated by Django 4.2.23 on 2025-07-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0012_shop_featured_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_shops',
            field=models.ManyToManyField(blank=True, help_text='Sklepy gdzie produkt jest dostępny', related_name='products_available', to='dzik.shop', verbose_name='Dostępny w sklepach'),
        ),
        migrations.AddField(
            model_name='shop',
            name='available_products',
            field=models.ManyToManyField(blank=True, help_text='Produkty dostępne w tym sklepie', related_name='shops_available', to='dzik.product', verbose_name='Produkty w sklepie'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='featured_products',
            field=models.ManyToManyField(blank=True, help_text='Główne produkty dostępne w tym sklepie', related_name='shops_featured', through='dzik.ProductShopRelation', to='dzik.product', verbose_name='Produkty w sklepie (przez relację)'),
        ),
    ]
