# Generated by Django 4.2.23 on 2025-07-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0013_product_available_shops_shop_available_products_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productshoprelation',
            options={'ordering': ['product__category', 'product__name', 'shop__name'], 'verbose_name': 'Produkt w sklepie', 'verbose_name_plural': 'Produkty w sklepach'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name'], 'verbose_name': 'Sklep', 'verbose_name_plural': 'Sklepy'},
        ),
        migrations.RemoveField(
            model_name='shop',
            name='chain',
        ),
        migrations.AlterField(
            model_name='product',
            name='available_shops',
            field=models.ManyToManyField(blank=True, related_name='products_available', to='dzik.shop', verbose_name='Dostępny w sklepach'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='available_products',
            field=models.ManyToManyField(blank=True, related_name='shops_available', to='dzik.product', verbose_name='Produkty w sklepie'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='featured_products',
            field=models.ManyToManyField(blank=True, related_name='shops_featured', through='dzik.ProductShopRelation', to='dzik.product', verbose_name='Produkty w sklepie (przez relację)'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='shop_logos/', verbose_name='Logo sieci'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nazwa sieci'),
        ),
    ]
