# Generated by Django 4.2.23 on 2025-07-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0015_shop_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='chain',
            field=models.CharField(choices=[('biedronka', 'Biedronka'), ('zabka', 'Żabka'), ('lidl', 'Lidl'), ('kaufland', 'Kaufland'), ('dino', 'Dino'), ('aldi', 'Aldi'), ('inter', 'Intermarché'), ('stokrotka', 'Stokrotka'), ('topaz', 'Topaz'), ('twoj_market', 'Twój Market'), ('carrefour', 'Carrefour'), ('dealz', 'Dealz'), ('other', 'Inne')], default='other', max_length=50, verbose_name='Sieć handlowa'),
        ),
    ]
