# Generated by Django 4.2.23 on 2025-07-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0016_alter_shop_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='OSMShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('chain', models.CharField(choices=[('biedronka', 'Biedronka'), ('zabka', 'Żabka'), ('lidl', 'Lidl'), ('kaufland', 'Kaufland'), ('dino', 'Dino'), ('aldi', 'Aldi'), ('inter', 'Intermarché'), ('stokrotka', 'Stokrotka'), ('topaz', 'Topaz'), ('twoj_market', 'Twój Market'), ('carrefour', 'Carrefour'), ('dealz', 'Dealz'), ('other', 'Inne')], max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shop_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dzik.shop')),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='dzik_osmsho_latitud_b8e2c7_idx'), models.Index(fields=['chain'], name='dzik_osmsho_chain_489ad5_idx'), models.Index(fields=['is_active'], name='dzik_osmsho_is_acti_3fe2c1_idx')],
            },
        ),
    ]
