# Generated by Django 4.2.23 on 2025-07-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0018_remove_osmshop_dzik_osmsho_chain_489ad5_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='osmshop',
            name='dzik_osmsho_chain_529158_idx',
        ),
        migrations.RemoveIndex(
            model_name='osmshop',
            name='dzik_osmsho_is_acti_807451_idx',
        ),
        migrations.RemoveIndex(
            model_name='osmshop',
            name='dzik_osmsho_latitud_562afc_idx',
        ),
        migrations.RemoveIndex(
            model_name='osmshop',
            name='dzik_osmsho_longitu_5dab1c_idx',
        ),
        migrations.AddIndex(
            model_name='osmshop',
            index=models.Index(fields=['chain'], name='dzik_osmsho_chain_489ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='osmshop',
            index=models.Index(fields=['is_active'], name='dzik_osmsho_is_acti_3fe2c1_idx'),
        ),
    ]
