# Generated by Django 4.2.23 on 2025-08-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0020_alter_osmshop_chain_alter_shop_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmshop',
            name='chain',
            field=models.CharField(choices=[('biedronka', 'Biedronka'), ('zabka', 'Żabka'), ('lidl', 'Lidl'), ('kaufland', 'Kaufland'), ('dino', 'Dino'), ('aldi', 'Aldi'), ('inter', 'Intermarché'), ('stokrotka', 'Stokrotka'), ('topaz', 'Topaz'), ('twoj_market', 'Twój Market'), ('carrefour', 'Carrefour'), ('dealz', 'Dealz'), ('auchan', 'Auchan'), ('selgros', 'Selgros'), ('eurocash', 'Eurocash Cash&Carry'), ('bp', 'BP'), ('circle_k', 'Circle K'), ('arhelan', 'Arhelan'), ('other', 'Inne')], max_length=50),
        ),
        migrations.AlterField(
            model_name='shop',
            name='chain',
            field=models.CharField(choices=[('biedronka', 'Biedronka'), ('zabka', 'Żabka'), ('lidl', 'Lidl'), ('kaufland', 'Kaufland'), ('dino', 'Dino'), ('aldi', 'Aldi'), ('inter', 'Intermarché'), ('stokrotka', 'Stokrotka'), ('topaz', 'Topaz'), ('twoj_market', 'Twój Market'), ('carrefour', 'Carrefour'), ('dealz', 'Dealz'), ('auchan', 'Auchan'), ('selgros', 'Selgros'), ('eurocash', 'Eurocash Cash&Carry'), ('bp', 'BP'), ('circle_k', 'Circle K'), ('arhelan', 'Arhelan'), ('other', 'Inne')], default='other', max_length=50, verbose_name='Sieć handlowa'),
        ),
    ]
