# Generated by Django 4.2.23 on 2025-08-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dzik', '0021_alter_osmshop_chain_alter_shop_chain'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('shop_not_exists', 'Sklep nie istnieje/zamknięty'), ('wrong_location', 'Zła lokalizacja na mapie'), ('no_products', 'Brak produktów DZIK w sklepie'), ('wrong_products', 'Inne produkty niż pokazane'), ('app_bug', 'Problem z mapą/wyszukiwaniem'), ('missing_shop', 'Brakujący sklep w okolicy'), ('feature_request', 'Sugestia/pomysł'), ('other', 'Inny problem')], max_length=50, verbose_name='Rodzaj problemu')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(verbose_name='Opis problemu')),
                ('user_email', models.EmailField(blank=True, max_length=254, verbose_name='Email (opcjonalnie)')),
                ('screenshot', models.ImageField(blank=True, upload_to='reports/', verbose_name='Zrzut ekranu')),
                ('shop_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Szerokość')),
                ('shop_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Długość')),
                ('shop_name', models.CharField(blank=True, max_length=200, verbose_name='Nazwa sklepu')),
                ('source', models.CharField(max_length=10, verbose_name='Źródło')),
                ('status', models.CharField(choices=[('new', 'Nowe'), ('resolved', 'Rozwiązane'), ('rejected', 'Odrzucone')], default='new', max_length=20, verbose_name='Status')),
                ('admin_response', models.TextField(blank=True, verbose_name='Odpowiedź administratora')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data zgłoszenia')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'Zgłoszenie użytkownika',
                'verbose_name_plural': 'Zgłoszenia użytkowników',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='dzik_userre_status_7d803c_idx'), models.Index(fields=['source'], name='dzik_userre_source_eb588e_idx')],
            },
        ),
    ]
